- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: shipping.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml


