- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: move jar file
  ansible.builtin.command: mv target/{{ component }}-*.jar {{ component }}.jar
  args:
    chdir: /app

- name: install dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app
