- name: copy {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
  nofity: daemon reload

- name: start the service
  ansible.builtin.systemd_service:
    name: "{{ component }}"
    state: restarted
    enabled: yes
